Release v1.0.0-alpha RC1 (#531)
* Issue refreshing the page creates new api token (#356)
* Fixed Refreshing the page creates new API token
* Remove gem amqp (#372)
* Ability to manage rails force_ssl option from environment (#361)
* Replace rest-client in favor of faraday & update rack-attack (fixes #337) (#348)
* [Fix #287] Change balance precision in markets. (#379)
* Create configuration variables which should be used to specify active OAuth2 providers (closes #299). (#357)
*  Add omniauth-barong gem(#376) (#385)
* Add omniauth-barong gem
* Omniauth initializers update
* Application.yml update(#376)
* Fiat deposit screen invalid protocol name (#374) (#378)
* Create admin rubric which allows to manually deposit USD (closes #300) (#354)
* Add GET (index only) & POST /withdrawals/addresses(#394) (#398)
* Added GET /withdraws/addresses api call
* Added POST /withdraws/addresses api call
* GET /withdraws/addresses specs
* POST /withdraws/addresses specs(#394)
* Ability to configure the PEATIO text which is displayed on the market page header(#391) (#393)
* Fix issue preventing Docker container from build. Also fix docs issues. (#400)
* BitGo support (#355)
* Add BCH & LTC support (#402)
* Add support for Bitcoin Cash (#331)
* Add support for Litecoin (closes #333).
* Remove Twilio leftovers from application.yml (#415)
* Add missing coin_api/ltc.rb (#416)
* Remove hardcoded host in API docs (fixes #367) (#417)
* Undefined method balance for CoinAPI::BitGo (#419)
* Add POST /api/v2/withdraws (closes #407) (#410)
* Make GOD log to STDOUT in Docker env (fixes #335) (#363)
* Fix ArgumentError (fixes #422) (#424)
* Add missing HTML code for «Solvency» page & change transparent background for LTC to white icon (#431)
* Add missing "entries" key for CoinAPI::BTC#load_deposit! and minor fixes for Bitcoind (#428)
* Add support for Dash (closes #346) (#425)
* Bugfixes for coins.rb & amqp:deposit_coin daemons found after BitGo integration. (#430)
* Update aasm to 4.x (closes #352)
* Security fixes according to Brakeman (closes #336)
* [Fix #301] Revert fund_source to fund_source_id. (#365)
* Add new rake task: accounts:touch (#436) (#450)
* Added opportunity set value of withdrawing fee in withdraw_channels.yml (#451) (#456)
* POST /api/v2/withdraws allows amount to be fraction number (#452) (#454)
* New withdraw amount test
* Fix #462: ActionView::Template::Error: wrong number of arguments (given 1, expected 0) at /admin/withdraws/banks (#463)
* Docker image tag mismatch & ability to use custom VERSION (#439) (#458)
* Add ability to define the base fiat currency  (#411)
* Fix markets switcher (#460) (#465)
* Frontend sign in through Peatio (#466)
* Fix specs falling due to #466 (#477)
* Markets switcher fix after ability to define the base fiat currency (#460) (#472)
* k_with_pending_trades fix undefined method '[]' error (#474)
* Remove state «almost_done» from withdraw and dispatch failed API calls to «failed» state (closes #476). (#478)
* Added api call for deleting withdraw address (#479)
* Remove duplicate stuff for currencies: rewrite loops, cleanup controllers & unify lot of views (#484)
* Add withdraw_channels & deposit_channels to generators (#486)
* Fix processing transaction behavior. (#500)
* If withdraw fails amount is put back to balance (#494) (#501)
* Fix errors preventing fiat deposit from working (#503) (#505)
* Revert "Create admin rubric which allows to manually deposit USD" (#483) (#504)
* Replace KyC with member level (#502)
* Add missing «Accept» button for withdraw (admin panel) (#515)
* Add ability to include custom stylesheets for markets page (#514)
* Add form to admin rubric which allows to manually create deposit (closes #506) (#509)
* Add ability to include custom stylesheet for landing, funds, api_v2 & application layouts.
* Replace ROTP gem in favor of custom generator (#523)
* Add missing Sentry at markets page (#527)
* Update omniauth-barong to 0.1.2 and lock the min version to the same (#526)
* Store OAuth2 access token for downloading profile in future. Add task barong:levels for refreshing access level for Barong members. (#525)
* Refactor fiat deposits to match new behavior (closes #507) (#528)
* Allow customizing page metadata: title, desc and keywords. (#529)